/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TableEmpty: typeof import('./components/TableDemo/TableEmpty.vue')['default']
    TableFixedAll: typeof import('./components/TableDemo/TableFixedAll.vue')['default']
    TableFixedAllAndPaginate: typeof import('./components/TableDemo/TableFixedAllAndPaginate.vue')['default']
    TableFixedHeader: typeof import('./components/TableDemo/TableFixedHeader.vue')['default']
    TableFixedLeft: typeof import('./components/TableDemo/TableFixedLeft.vue')['default']
    TableFixedLeftAndRight: typeof import('./components/TableDemo/TableFixedLeftAndRight.vue')['default']
    TableLoading: typeof import('./components/TableDemo/TableLoading.vue')['default']
    TableNormal: typeof import('./components/TableDemo/TableNormal.vue')['default']
    TablePagination: typeof import('./components/TablePagination/index.vue')['default']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanIcon: typeof import('vant/es')['Icon']
    VanPagination: typeof import('vant/es')['Pagination']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
